# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "crafty_settings",
        og_enabled=peewee.BooleanField(default=True),
        og_title=peewee.CharField(default=""),
        og_description=peewee.CharField(default=""),
        og_image=peewee.CharField(default=""),
        og_color=peewee.CharField(default="#005cd1"),
    )


def rollback(migrator, database, **kwargs):
    migrator.drop_columns(
        "crafty_settings",
        ["og_enabled", "og_title", "og_description", "og_image", "og_color"],
    )
