# Generated by database migrator
import peewee


def migrate(migrator, database, **kwargs):
    migrator.add_columns(
        "crafty_settings",
        logo_full=peewee.CharField(default=""),
        logo_square=peewee.CharField(default=""),
    )


def rollback(migrator, database, **kwargs):
    migrator.drop_columns(
        "crafty_settings",
        ["logo_full", "logo_square"],
    )
